# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/nam/edabk_new_project/PULP/pulpissimo/fpga/pulpissimo-kc705-ver2/constraints/kc705.xdc

# IP: /home/nam/edabk_new_project/PULP/pulpissimo/fpga/pulpissimo-kc705-ver2/ips/xilinx_clk_mngr/xilinx_clk_mngr.srcs/sources_1/ip/xilinx_clk_mngr/xilinx_clk_mngr.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xilinx_clk_mngr || ORIG_REF_NAME==xilinx_clk_mngr} -quiet] -quiet

# IP: /home/nam/edabk_new_project/PULP/pulpissimo/fpga/pulpissimo-kc705-ver2/ips/xilinx_slow_clk_mngr/xilinx_slow_clk_mngr.srcs/sources_1/ip/xilinx_slow_clk_mngr/xilinx_slow_clk_mngr.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xilinx_slow_clk_mngr || ORIG_REF_NAME==xilinx_slow_clk_mngr} -quiet] -quiet
