# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache ./.Xil/Vivado-384524-edabknam/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7k325tffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/nam/edabk_new_project/PULP/pulpissimo/fpga/pulpissimo-kc705-ver2/pulpissimo-kc705.cache/wt [current_project]
set_property parent.project_path /home/nam/edabk_new_project/PULP/pulpissimo/fpga/pulpissimo-kc705-ver2/pulpissimo-kc705.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:kc705:part0:1.6 [current_project]
set_property ip_output_repo /home/nam/edabk_new_project/PULP/pulpissimo/fpga/pulpissimo-kc705-ver2/pulpissimo-kc705.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
set_property include_dirs {
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/adv_dbg_if-5b6b130a03a5c9fc/rtl
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/apb_adv_timer-4c5b7c37534a8b97/rtl
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/axi-6ba48e7137b8faf2/include
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/cluster_interconnect-cd2e76203435860b/rtl/low_latency_interco
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/cluster_interconnect-cd2e76203435860b/rtl/peripheral_interco
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/common_cells-a025d4426209aa2e/include
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/cv32e40p-1bd0b2f06e9c89fa/bhv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/cv32e40p-1bd0b2f06e9c89fa/rtl/include
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/hwpe-ctrl-84441a57cfe35450/rtl
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/hwpe-mac-engine-bda8f57a02fedb57/rtl
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/hwpe-stream-3d98101b35dad7de/rtl
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/ibex-1ed1f888f0ee8d9a/rtl
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/ibex-1ed1f888f0ee8d9a/vendor/lowrisc_ip/ip/prim/rtl
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/pulp_soc-426e7b7e589fbdfe/rtl/include
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/register_interface-eb9e866f3e0731e1/include
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_core-4dfb66675047f408/rtl
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_i2c-b6d6aa6271adcd0c/rtl
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_qspi-a05abba6367cd932/rtl
  /home/nam/edabk_new_project/PULP/pulpissimo/rtl/includes
} [current_fileset]
set_property verilog_define {FPGA_TARGET_XILINX=1 PULP_FPGA_EMUL=1 AXI4_XCHECK_OFF=1} [current_fileset]
read_verilog -library xil_defaultlib -sv {
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/adv_dbg_if-5b6b130a03a5c9fc/rtl/adbg_lint_biu.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/adv_dbg_if-5b6b130a03a5c9fc/rtl/adbg_lint_module.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/adv_dbg_if-5b6b130a03a5c9fc/rtl/adbg_lintonly_top.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/cluster_interconnect-cd2e76203435860b/rtl/tcdm_interconnect/addr_dec_resp_mux.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/common_cells-a025d4426209aa2e/src/cf_math_pkg.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/common_cells-a025d4426209aa2e/src/addr_decode.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/apb_adv_timer-4c5b7c37534a8b97/rtl/adv_timer_apb_if.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/apb2per-bc68f149a1a71c65/apb2per.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/apb_adv_timer-4c5b7c37534a8b97/rtl/apb_adv_timer.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/apb_fll_if-5962ef2c8b18132f/src/apb_fll_if.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/apb_gpio-73dcd13fa1d206d0/rtl/apb_gpio.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/apb_interrupt_cntrl-4b871747a33caa87/apb_interrupt_cntrl.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/apb-aabe5a48cb887de0/src/apb_intf.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/apb_node-228204d192c97749/src/apb_node.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/apb_node-228204d192c97749/src/apb_node_wrap.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/pulp_soc-426e7b7e589fbdfe/rtl/components/apb_soc_ctrl.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/timer_unit-a67731aa2e00940e/rtl/apb_timer_unit.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/l2_tcdm_hybrid_interco-6f75bb3937609e47/RTL/axi_2_lint/axi64_2_lint32.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/pulp_soc-426e7b7e589fbdfe/rtl/pulp_soc/axi64_2_lint32_wrap.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/axi_slice-8afc001fc8656540/src/axi_ar_buffer.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/axi-6ba48e7137b8faf2/src/axi_pkg.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/axi-6ba48e7137b8faf2/src/axi_atop_filter.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/axi_slice-8afc001fc8656540/src/axi_aw_buffer.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/axi_slice-8afc001fc8656540/src/axi_b_buffer.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/axi-6ba48e7137b8faf2/src/axi_burst_splitter.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/axi-6ba48e7137b8faf2/src/axi_cdc_dst.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/axi-6ba48e7137b8faf2/src/axi_cdc_src.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/axi-6ba48e7137b8faf2/src/axi_demux.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/axi-6ba48e7137b8faf2/src/axi_err_slv.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/axi-6ba48e7137b8faf2/src/axi_id_prepend.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/axi-6ba48e7137b8faf2/src/axi_intf.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/axi-6ba48e7137b8faf2/src/axi_lite_to_apb.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/axi-6ba48e7137b8faf2/src/axi_mux.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/axi_slice-8afc001fc8656540/src/axi_r_buffer.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/l2_tcdm_hybrid_interco-6f75bb3937609e47/RTL/axi_2_lint/axi_read_ctrl.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/axi_slice-8afc001fc8656540/src/axi_single_slice.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/axi-6ba48e7137b8faf2/src/axi_to_axi_lite.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/axi_slice-8afc001fc8656540/src/axi_w_buffer.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/l2_tcdm_hybrid_interco-6f75bb3937609e47/RTL/axi_2_lint/axi_write_ctrl.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/axi-6ba48e7137b8faf2/src/axi_xbar.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/common_cells-a025d4426209aa2e/src/binary_to_gray.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/pulp_soc-426e7b7e589fbdfe/rtl/pulp_soc/boot_rom.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/jtag_pulp-670643485f6ff26e/src/bscell.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_camera-21de0a4f6e514abd/rtl/camera_if.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_camera-21de0a4f6e514abd/rtl/camera_reg_if.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/common_cells-a025d4426209aa2e/src/cdc_2phase_clearable.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/common_cells-a025d4426209aa2e/src/cdc_4phase.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/common_cells-a025d4426209aa2e/src/cdc_fifo_gray.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_hyper-268b385f057e6bde/udma-hyperbus/src/cdc_fifo_gray_hyper.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/common_cells-a025d4426209aa2e/src/cdc_reset_ctrlr_pkg.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/common_cells-a025d4426209aa2e/src/cdc_reset_ctrlr.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_i2s-918ee355380d7093/rtl/cic_comb.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_i2s-918ee355380d7093/rtl/cic_integrator.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_i2s-918ee355380d7093/rtl/cic_top.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_hyper-268b385f057e6bde/udma-hyperbus/src/clk_gen_hyper.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_hyper-268b385f057e6bde/udma-hyperbus/src/clock_diff_out.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/tech_cells_generic-f82f6dfe2108e16b/src/deprecated/cluster_clk_cells.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_hyper-268b385f057e6bde/udma-hyperbus/src/cmd_addr_gen.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/apb_adv_timer-4c5b7c37534a8b97/rtl/comparator.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/pulp_soc-426e7b7e589fbdfe/rtl/pulp_soc/pkg_soc_interconnect.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/pulp_soc-426e7b7e589fbdfe/rtl/pulp_soc/contiguous_crossbar.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/fpu_div_sqrt_mvp-de98fb0e82931ead/hdl/defs_div_sqrt_mvp.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/fpu_div_sqrt_mvp-de98fb0e82931ead/hdl/control_mvp.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/common_cells-a025d4426209aa2e/src/counter.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/cv32e40p-1bd0b2f06e9c89fa/rtl/cv32e40p_aligner.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/cv32e40p-1bd0b2f06e9c89fa/rtl/include/cv32e40p_pkg.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/cv32e40p-1bd0b2f06e9c89fa/rtl/cv32e40p_alu.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/cv32e40p-1bd0b2f06e9c89fa/rtl/cv32e40p_alu_div.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/cv32e40p-1bd0b2f06e9c89fa/rtl/include/cv32e40p_apu_core_pkg.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/cv32e40p-1bd0b2f06e9c89fa/rtl/cv32e40p_apu_disp.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/fpga/pulpissimo-kc705-ver2/rtl/cv32e40p_clock_gate_xilinx.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/cv32e40p-1bd0b2f06e9c89fa/rtl/cv32e40p_compressed_decoder.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/cv32e40p-1bd0b2f06e9c89fa/rtl/cv32e40p_controller.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/cv32e40p-1bd0b2f06e9c89fa/rtl/cv32e40p_core.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/cv32e40p-1bd0b2f06e9c89fa/rtl/cv32e40p_cs_registers.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/cv32e40p-1bd0b2f06e9c89fa/rtl/include/cv32e40p_fpu_pkg.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/cv32e40p-1bd0b2f06e9c89fa/rtl/cv32e40p_decoder.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/cv32e40p-1bd0b2f06e9c89fa/rtl/cv32e40p_ex_stage.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/cv32e40p-1bd0b2f06e9c89fa/rtl/cv32e40p_ff_one.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/cv32e40p-1bd0b2f06e9c89fa/rtl/cv32e40p_fifo.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/fpnew-62313c8dc613cd59/src/fpnew_pkg.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/pulp_soc-426e7b7e589fbdfe/rtl/fc/cv32e40p_fp_wrapper.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/cv32e40p-1bd0b2f06e9c89fa/rtl/cv32e40p_hwloop_regs.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/cv32e40p-1bd0b2f06e9c89fa/rtl/cv32e40p_id_stage.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/cv32e40p-1bd0b2f06e9c89fa/rtl/cv32e40p_if_stage.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/cv32e40p-1bd0b2f06e9c89fa/rtl/cv32e40p_int_controller.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/cv32e40p-1bd0b2f06e9c89fa/rtl/cv32e40p_load_store_unit.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/cv32e40p-1bd0b2f06e9c89fa/rtl/cv32e40p_mult.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/cv32e40p-1bd0b2f06e9c89fa/rtl/cv32e40p_obi_interface.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/cv32e40p-1bd0b2f06e9c89fa/rtl/cv32e40p_popcnt.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/cv32e40p-1bd0b2f06e9c89fa/rtl/cv32e40p_prefetch_buffer.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/cv32e40p-1bd0b2f06e9c89fa/rtl/cv32e40p_prefetch_controller.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/cv32e40p-1bd0b2f06e9c89fa/rtl/cv32e40p_register_file_ff.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/cv32e40p-1bd0b2f06e9c89fa/rtl/cv32e40p_sleep_unit.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_hyper-268b385f057e6bde/udma-hyperbus/src/dc_data_buffer_hyper.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_hyper-268b385f057e6bde/udma-hyperbus/src/ddr_out.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/riscv-dbg-7c98112a0e15ffb0/debug_rom/debug_rom.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/riscv-dbg-7c98112a0e15ffb0/debug_rom/debug_rom_one_scratch.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/common_cells-a025d4426209aa2e/src/delta_counter.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/fpu_div_sqrt_mvp-de98fb0e82931ead/hdl/div_sqrt_top_mvp.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/riscv-dbg-7c98112a0e15ffb0/src/dm_pkg.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/riscv-dbg-7c98112a0e15ffb0/src/dm_csrs.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/riscv-dbg-7c98112a0e15ffb0/src/dm_mem.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/riscv-dbg-7c98112a0e15ffb0/src/dm_sba.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/riscv-dbg-7c98112a0e15ffb0/src/dm_top.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/riscv-dbg-7c98112a0e15ffb0/src/dmi_cdc.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/riscv-dbg-7c98112a0e15ffb0/src/dmi_jtag.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/riscv-dbg-7c98112a0e15ffb0/src/dmi_jtag_tap.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/common_cells-a025d4426209aa2e/src/edge_propagator.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/common_cells-a025d4426209aa2e/src/edge_propagator_ack.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/common_cells-a025d4426209aa2e/src/edge_propagator_rx.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/common_cells-a025d4426209aa2e/src/edge_propagator_tx.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/common_cells-a025d4426209aa2e/src/fall_through_register.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/pulp_soc-426e7b7e589fbdfe/rtl/fc/fc_hwpe.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/ibex-1ed1f888f0ee8d9a/rtl/ibex_pkg.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/pulp_soc-426e7b7e589fbdfe/rtl/fc/fc_subsystem.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/common_cells-a025d4426209aa2e/src/deprecated/fifo_v1.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/common_cells-a025d4426209aa2e/src/deprecated/fifo_v2.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/common_cells-a025d4426209aa2e/src/fifo_v3.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/apb_fll_if-5962ef2c8b18132f/src/fll_intf.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/fpga/pulpissimo-kc705-ver2/rtl/fpga_bootrom.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/fpga/pulpissimo-kc705-ver2/rtl/fpga_clk_gen.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/fpga/pulpissimo-kc705-ver2/rtl/fpga_slow_clk_gen.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/fpnew-62313c8dc613cd59/src/fpnew_cast_multi.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/fpnew-62313c8dc613cd59/src/fpnew_classifier.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/fpnew-62313c8dc613cd59/src/fpnew_divsqrt_multi.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/fpnew-62313c8dc613cd59/src/fpnew_fma.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/fpnew-62313c8dc613cd59/src/fpnew_fma_multi.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/fpnew-62313c8dc613cd59/src/fpnew_noncomp.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/fpnew-62313c8dc613cd59/src/fpnew_opgroup_block.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/fpnew-62313c8dc613cd59/src/fpnew_opgroup_fmt_slice.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/fpnew-62313c8dc613cd59/src/fpnew_opgroup_multifmt_slice.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/fpnew-62313c8dc613cd59/src/fpnew_rounding.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/fpnew-62313c8dc613cd59/src/fpnew_top.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/common_cells-a025d4426209aa2e/src/deprecated/generic_fifo.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/common_cells-a025d4426209aa2e/src/gray_to_binary.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_hyper-268b385f057e6bde/udma-hyperbus/src/graycode_hyper.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/hwpe-ctrl-84441a57cfe35450/rtl/hwpe_ctrl_interfaces.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/hwpe-ctrl-84441a57cfe35450/rtl/hwpe_ctrl_package.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/hwpe-ctrl-84441a57cfe35450/rtl/hwpe_ctrl_regfile.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/hwpe-ctrl-84441a57cfe35450/rtl/hwpe_ctrl_regfile_latch.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/hwpe-ctrl-84441a57cfe35450/rtl/hwpe_ctrl_regfile_latch_test_wrap.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/hwpe-ctrl-84441a57cfe35450/rtl/hwpe_ctrl_slave.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/hwpe-ctrl-84441a57cfe35450/rtl/hwpe_ctrl_uloop.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/hwpe-stream-3d98101b35dad7de/rtl/hwpe_stream_package.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/hwpe-stream-3d98101b35dad7de/rtl/streamer/hwpe_stream_addressgen.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/hwpe-stream-3d98101b35dad7de/rtl/basic/hwpe_stream_assign.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/hwpe-stream-3d98101b35dad7de/rtl/basic/hwpe_stream_fence.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/hwpe-stream-3d98101b35dad7de/rtl/fifo/hwpe_stream_fifo.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/hwpe-stream-3d98101b35dad7de/rtl/fifo/hwpe_stream_fifo_scm.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/hwpe-stream-3d98101b35dad7de/rtl/fifo/hwpe_stream_fifo_scm_test_wrap.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/hwpe-stream-3d98101b35dad7de/rtl/hwpe_stream_interfaces.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/hwpe-stream-3d98101b35dad7de/rtl/basic/hwpe_stream_merge.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/hwpe-stream-3d98101b35dad7de/rtl/streamer/hwpe_stream_sink.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/hwpe-stream-3d98101b35dad7de/rtl/streamer/hwpe_stream_sink_realign.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/hwpe-stream-3d98101b35dad7de/rtl/streamer/hwpe_stream_source.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/hwpe-stream-3d98101b35dad7de/rtl/streamer/hwpe_stream_source_realign.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/hwpe-stream-3d98101b35dad7de/rtl/basic/hwpe_stream_split.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/hwpe-stream-3d98101b35dad7de/rtl/tcdm/hwpe_stream_tcdm_fifo_load.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/hwpe-stream-3d98101b35dad7de/rtl/tcdm/hwpe_stream_tcdm_fifo_store.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_hyper-268b385f057e6bde/udma-hyperbus/src/hyper_arb_primitive.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_hyper-268b385f057e6bde/udma-hyperbus/src/hyper_arbiter.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_hyper-268b385f057e6bde/udma-hyperbus/src/hyper_rr_flag_req.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_hyper-268b385f057e6bde/udma-hyperbus/src/hyper_twd_trans_spliter.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_hyper-268b385f057e6bde/udma-hyperbus/src/hyper_unpack.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_hyper-268b385f057e6bde/udma-hyperbus/src/hyperbus_delay_line.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_hyper-268b385f057e6bde/udma-hyperbus/src/hyperbus_mux_generic.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_hyper-268b385f057e6bde/udma-hyperbus/src/hyperbus_phy.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_i2s-918ee355380d7093/rtl/i2s_clk_gen.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_i2s-918ee355380d7093/rtl/i2s_clkws_gen.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_i2s-918ee355380d7093/rtl/i2s_rx_channel.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_i2s-918ee355380d7093/rtl/i2s_tx_channel.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_i2s-918ee355380d7093/rtl/i2s_txrx.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_i2s-918ee355380d7093/rtl/i2s_ws_gen.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/ibex-1ed1f888f0ee8d9a/rtl/ibex_alu.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/ibex-1ed1f888f0ee8d9a/vendor/lowrisc_ip/ip/prim/rtl/prim_assert.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/ibex-1ed1f888f0ee8d9a/rtl/ibex_compressed_decoder.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/ibex-1ed1f888f0ee8d9a/rtl/ibex_controller.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/ibex-1ed1f888f0ee8d9a/rtl/ibex_core.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/ibex-1ed1f888f0ee8d9a/rtl/ibex_counter.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/ibex-1ed1f888f0ee8d9a/rtl/ibex_cs_registers.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/ibex-1ed1f888f0ee8d9a/rtl/ibex_csr.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/ibex-1ed1f888f0ee8d9a/rtl/ibex_decoder.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/ibex-1ed1f888f0ee8d9a/rtl/ibex_ex_block.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/ibex-1ed1f888f0ee8d9a/rtl/ibex_fetch_fifo.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/ibex-1ed1f888f0ee8d9a/rtl/ibex_id_stage.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/ibex-1ed1f888f0ee8d9a/rtl/ibex_if_stage.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/ibex-1ed1f888f0ee8d9a/rtl/ibex_load_store_unit.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/ibex-1ed1f888f0ee8d9a/rtl/ibex_multdiv_fast.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/ibex-1ed1f888f0ee8d9a/rtl/ibex_multdiv_slow.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/ibex-1ed1f888f0ee8d9a/rtl/ibex_pmp.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/ibex-1ed1f888f0ee8d9a/rtl/ibex_prefetch_buffer.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/ibex-1ed1f888f0ee8d9a/rtl/ibex_register_file_ff.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/ibex-1ed1f888f0ee8d9a/rtl/ibex_register_file_fpga.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/ibex-1ed1f888f0ee8d9a/rtl/ibex_register_file_latch.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/ibex-1ed1f888f0ee8d9a/rtl/ibex_wb_stage.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/common_cells-a025d4426209aa2e/src/id_queue.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/apb_adv_timer-4c5b7c37534a8b97/rtl/input_stage.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/pulp_soc-426e7b7e589fbdfe/rtl/pulp_soc/interleaved_crossbar.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_core-4dfb66675047f408/rtl/common/io_generic_fifo.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_hyper-268b385f057e6bde/udma-hyperbus/src/io_generic_fifo_hyper.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_core-4dfb66675047f408/rtl/common/io_tx_fifo.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_core-4dfb66675047f408/rtl/common/io_tx_fifo_mark.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/fpu_div_sqrt_mvp-de98fb0e82931ead/hdl/iteration_div_sqrt_mvp.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/jtag_pulp-670643485f6ff26e/src/jtag_sync.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/rtl/pulpissimo/jtag_tap_top.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/jtag_pulp-670643485f6ff26e/src/jtagreg.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/pulp_soc-426e7b7e589fbdfe/rtl/pulp_soc/l2_ram_multi_bank.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/l2_tcdm_hybrid_interco-6f75bb3937609e47/RTL/axi_2_lint/lint64_to_32.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/l2_tcdm_hybrid_interco-6f75bb3937609e47/RTL/lint_2_axi.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/pulp_soc-426e7b7e589fbdfe/rtl/pulp_soc/lint_2_axi_wrap.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/pulp_soc-426e7b7e589fbdfe/rtl/pulp_soc/lint_jtag_wrap.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/common_cells-a025d4426209aa2e/src/lzc.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/hwpe-mac-engine-bda8f57a02fedb57/rtl/mac_package.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/hwpe-mac-engine-bda8f57a02fedb57/rtl/mac_ctrl.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/hwpe-mac-engine-bda8f57a02fedb57/rtl/mac_engine.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/hwpe-mac-engine-bda8f57a02fedb57/rtl/mac_fsm.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/hwpe-mac-engine-bda8f57a02fedb57/rtl/mac_streamer.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/hwpe-mac-engine-bda8f57a02fedb57/rtl/mac_top.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/hwpe-mac-engine-bda8f57a02fedb57/wrap/mac_top_wrap.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/fpu_div_sqrt_mvp-de98fb0e82931ead/hdl/norm_div_sqrt_mvp.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/fpu_div_sqrt_mvp-de98fb0e82931ead/hdl/nrbd_nrsc_mvp.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/pulp_soc-426e7b7e589fbdfe/rtl/components/obi_pulp_adapter.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/common_cells-a025d4426209aa2e/src/onehot_to_bin.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_hyper-268b385f057e6bde/udma-hyperbus/src/onehot_to_bin_hyper.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/rtl/pulpissimo/pad_control.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/rtl/pulpissimo/pad_frame.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/fpga/pulpissimo-kc705-ver2/rtl/pad_functional_xilinx.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_i2s-918ee355380d7093/rtl/pdm_top.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/pulp_soc-426e7b7e589fbdfe/rtl/pulp_soc/periph_bus_wrap.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/fpu_div_sqrt_mvp-de98fb0e82931ead/hdl/preprocess_mvp.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/apb_adv_timer-4c5b7c37534a8b97/rtl/prescaler.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/tech_cells_generic-f82f6dfe2108e16b/src/deprecated/pulp_clk_cells.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/tech_cells_generic-f82f6dfe2108e16b/src/deprecated/pulp_clock_gating_async.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/fpga/pulpissimo-kc705-ver2/rtl/pulp_clock_gating_xilinx.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/pulp_soc-426e7b7e589fbdfe/rtl/components/pulp_interfaces.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/pulp_soc-426e7b7e589fbdfe/rtl/pulp_soc/pulp_soc.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/common_cells-a025d4426209aa2e/src/deprecated/pulp_sync.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/common_cells-a025d4426209aa2e/src/deprecated/pulp_sync_wedge.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/rtl/pulpissimo/pulpissimo.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_hyper-268b385f057e6bde/udma-hyperbus/src/read_clk_rwds.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/common_cells-a025d4426209aa2e/src/rr_arb_tree.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/rtl/pulpissimo/safe_domain.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_sdio-7584095ad0ee539b/rtl/sdio_crc16.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_sdio-7584095ad0ee539b/rtl/sdio_crc7.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_sdio-7584095ad0ee539b/rtl/sdio_txrx.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_sdio-7584095ad0ee539b/rtl/sdio_txrx_cmd.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_sdio-7584095ad0ee539b/rtl/sdio_txrx_data.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/pulp_soc-426e7b7e589fbdfe/rtl/pulp_soc/soc_clk_rst_gen.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/rtl/pulpissimo/soc_domain.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/pulp_soc-426e7b7e589fbdfe/rtl/pulp_soc/soc_event_arbiter.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/pulp_soc-426e7b7e589fbdfe/rtl/pulp_soc/soc_event_generator.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/pulp_soc-426e7b7e589fbdfe/rtl/pulp_soc/soc_event_queue.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/pulp_soc-426e7b7e589fbdfe/rtl/pulp_soc/soc_interconnect.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/pulp_soc-426e7b7e589fbdfe/rtl/pulp_soc/soc_interconnect_wrap.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/pulp_soc-426e7b7e589fbdfe/rtl/pulp_soc/soc_peripherals.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/common_cells-a025d4426209aa2e/src/spill_register.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/common_cells-a025d4426209aa2e/src/spill_register_flushable.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/common_cells-a025d4426209aa2e/src/stream_register.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/common_cells-a025d4426209aa2e/src/sync.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/tech_cells_generic-f82f6dfe2108e16b/src/fpga/tc_clk_xilinx.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/tech_cells_generic-f82f6dfe2108e16b/src/fpga/tc_sram_xilinx.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/pulp_soc-426e7b7e589fbdfe/rtl/components/tcdm_arbiter_2x1.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/pulp_soc-426e7b7e589fbdfe/rtl/pulp_soc/tcdm_demux.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/pulp_soc-426e7b7e589fbdfe/rtl/pulp_soc/tcdm_error_slave.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/apb_adv_timer-4c5b7c37534a8b97/rtl/timer_cntrl.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/apb_adv_timer-4c5b7c37534a8b97/rtl/timer_module.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/timer_unit-a67731aa2e00940e/rtl/timer_unit_counter.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/timer_unit-a67731aa2e00940e/rtl/timer_unit_counter_presc.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_core-4dfb66675047f408/rtl/common/udma_apb_if.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_core-4dfb66675047f408/rtl/core/udma_arbiter.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_hyper-268b385f057e6bde/udma-hyperbus/src/udma_cfg_outbuff.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_core-4dfb66675047f408/rtl/core/udma_ch_addrgen.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_core-4dfb66675047f408/rtl/common/udma_clk_div_cnt.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_core-4dfb66675047f408/rtl/common/udma_clkgen.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_hyper-268b385f057e6bde/udma-hyperbus/src/udma_cmd_queue.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_core-4dfb66675047f408/rtl/core/udma_core.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_core-4dfb66675047f408/rtl/common/udma_ctrl.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_core-4dfb66675047f408/rtl/common/udma_dc_fifo.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_hyper-268b385f057e6bde/udma-hyperbus/src/udma_dc_fifo_hyper.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_filter-c279f5816e82760e/rtl/udma_filter.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_filter-c279f5816e82760e/rtl/udma_filter_au.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_filter-c279f5816e82760e/rtl/udma_filter_bincu.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_filter-c279f5816e82760e/rtl/udma_filter_reg_if.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_filter-c279f5816e82760e/rtl/udma_filter_rx_dataout.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_filter-c279f5816e82760e/rtl/udma_filter_tx_datafetch.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_hyper-268b385f057e6bde/udma-hyperbus/src/udma_hyper_busy.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_hyper-268b385f057e6bde/udma-hyperbus/src/udma_hyper_busy_phy.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_hyper-268b385f057e6bde/udma-hyperbus/src/udma_hyper_ctrl.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_hyper-268b385f057e6bde/udma-hyperbus/src/udma_hyper_reg_if_common.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_hyper-268b385f057e6bde/udma-hyperbus/src/udma_hyper_reg_if_mulid.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_hyper-268b385f057e6bde/udma-hyperbus/src/udma_hyper_top.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_hyper-268b385f057e6bde/udma-hyperbus/src/udma_hyperbus_mulid.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_i2c-b6d6aa6271adcd0c/rtl/udma_i2c_bus_ctrl.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_i2c-b6d6aa6271adcd0c/rtl/udma_i2c_control.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_i2c-b6d6aa6271adcd0c/rtl/udma_i2c_reg_if.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_i2c-b6d6aa6271adcd0c/rtl/udma_i2c_top.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_i2s-918ee355380d7093/rtl/udma_i2s_reg_if.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_i2s-918ee355380d7093/rtl/udma_i2s_top.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_core-4dfb66675047f408/rtl/core/udma_rx_channels.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_hyper-268b385f057e6bde/udma-hyperbus/src/udma_rxbuffer.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_sdio-7584095ad0ee539b/rtl/udma_sdio_reg_if.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_sdio-7584095ad0ee539b/rtl/udma_sdio_top.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_qspi-a05abba6367cd932/rtl/udma_spim_ctrl.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_qspi-a05abba6367cd932/rtl/udma_spim_reg_if.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_qspi-a05abba6367cd932/rtl/udma_spim_top.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_qspi-a05abba6367cd932/rtl/udma_spim_txrx.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_core-4dfb66675047f408/rtl/core/udma_stream_unit.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/pulp_soc-426e7b7e589fbdfe/rtl/udma_subsystem/udma_subsystem.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_core-4dfb66675047f408/rtl/core/udma_tx_channels.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_hyper-268b385f057e6bde/udma-hyperbus/src/udma_txbuffer.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_uart-82cad1f1ac2c700c/rtl/udma_uart_reg_if.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_uart-82cad1f1ac2c700c/rtl/udma_uart_rx.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_uart-82cad1f1ac2c700c/rtl/udma_uart_top.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_uart-82cad1f1ac2c700c/rtl/udma_uart_tx.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/apb_adv_timer-4c5b7c37534a8b97/rtl/up_down_counter.sv
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/cluster_interconnect-cd2e76203435860b/rtl/tcdm_interconnect/xbar.sv
}
read_verilog -library xil_defaultlib {
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/adv_dbg_if-5b6b130a03a5c9fc/rtl/adbg_crc32.v
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_hyper-268b385f057e6bde/udma-hyperbus/src/dc_full_detector_hyper.v
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_hyper-268b385f057e6bde/udma-hyperbus/src/dc_synchronizer_hyper.v
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_hyper-268b385f057e6bde/udma-hyperbus/src/dc_token_ring_fifo_din_hyper.v
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_hyper-268b385f057e6bde/udma-hyperbus/src/dc_token_ring_fifo_dout_hyper.v
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/udma_hyper-268b385f057e6bde/udma-hyperbus/src/dc_token_ring_hyper.v
  /home/nam/edabk_new_project/PULP/pulpissimo/.bender/git/checkouts/jtag_pulp-670643485f6ff26e/src/tap_top.v
  /home/nam/edabk_new_project/PULP/pulpissimo/fpga/pulpissimo-kc705-ver2/rtl/xilinx_pulpissimo.v
}
read_ip -quiet /home/nam/edabk_new_project/PULP/pulpissimo/fpga/pulpissimo-kc705-ver2/ips/xilinx_clk_mngr/xilinx_clk_mngr.srcs/sources_1/ip/xilinx_clk_mngr/xilinx_clk_mngr.xci
set_property used_in_implementation false [get_files -all /home/nam/edabk_new_project/PULP/pulpissimo/fpga/pulpissimo-kc705-ver2/ips/xilinx_clk_mngr/xilinx_clk_mngr.srcs/sources_1/ip/xilinx_clk_mngr/xilinx_clk_mngr_board.xdc]
set_property used_in_implementation false [get_files -all /home/nam/edabk_new_project/PULP/pulpissimo/fpga/pulpissimo-kc705-ver2/ips/xilinx_clk_mngr/xilinx_clk_mngr.srcs/sources_1/ip/xilinx_clk_mngr/xilinx_clk_mngr.xdc]
set_property used_in_implementation false [get_files -all /home/nam/edabk_new_project/PULP/pulpissimo/fpga/pulpissimo-kc705-ver2/ips/xilinx_clk_mngr/xilinx_clk_mngr.srcs/sources_1/ip/xilinx_clk_mngr/xilinx_clk_mngr_ooc.xdc]

read_ip -quiet /home/nam/edabk_new_project/PULP/pulpissimo/fpga/pulpissimo-kc705-ver2/ips/xilinx_slow_clk_mngr/xilinx_slow_clk_mngr.srcs/sources_1/ip/xilinx_slow_clk_mngr/xilinx_slow_clk_mngr.xci
set_property used_in_implementation false [get_files -all /home/nam/edabk_new_project/PULP/pulpissimo/fpga/pulpissimo-kc705-ver2/ips/xilinx_slow_clk_mngr/xilinx_slow_clk_mngr.srcs/sources_1/ip/xilinx_slow_clk_mngr/xilinx_slow_clk_mngr_board.xdc]
set_property used_in_implementation false [get_files -all /home/nam/edabk_new_project/PULP/pulpissimo/fpga/pulpissimo-kc705-ver2/ips/xilinx_slow_clk_mngr/xilinx_slow_clk_mngr.srcs/sources_1/ip/xilinx_slow_clk_mngr/xilinx_slow_clk_mngr.xdc]
set_property used_in_implementation false [get_files -all /home/nam/edabk_new_project/PULP/pulpissimo/fpga/pulpissimo-kc705-ver2/ips/xilinx_slow_clk_mngr/xilinx_slow_clk_mngr.srcs/sources_1/ip/xilinx_slow_clk_mngr/xilinx_slow_clk_mngr_late.xdc]
set_property used_in_implementation false [get_files -all /home/nam/edabk_new_project/PULP/pulpissimo/fpga/pulpissimo-kc705-ver2/ips/xilinx_slow_clk_mngr/xilinx_slow_clk_mngr.srcs/sources_1/ip/xilinx_slow_clk_mngr/xilinx_slow_clk_mngr_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/nam/edabk_new_project/PULP/pulpissimo/fpga/pulpissimo-kc705-ver2/constraints/kc705.xdc
set_property used_in_implementation false [get_files /home/nam/edabk_new_project/PULP/pulpissimo/fpga/pulpissimo-kc705-ver2/constraints/kc705.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top xilinx_pulpissimo -part xc7k325tffg900-2 -flatten_hierarchy none -sfcu


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef xilinx_pulpissimo.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file xilinx_pulpissimo_utilization_synth.rpt -pb xilinx_pulpissimo_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
